// Stone-arch mark: voussoir ring with a raised keystone, quoined jambs and a sill.
const f = (n) => +n.toFixed(2);
export function markPath({ n = 9, cx = 24, spring = 23, R = 21, r = 15, keyExtra = 2, gapDeg = 2.6, courses = 4, jambBottom = 60, gap = 1.3, quoin = 1.6, sill = true } = {}) {
  const parts = [];
  const seg = (180 - gapDeg * (n - 1)) / n;
  const mid = (n - 1) / 2;
  const p = (rad, deg) => [cx + rad * Math.cos((deg * Math.PI) / 180), spring - rad * Math.sin((deg * Math.PI) / 180)];
  for (let i = 0; i < n; i++) {
    const a0 = 180 - i * (seg + gapDeg), a1 = a0 - seg;
    const key = i === mid;
    const Ro = key ? R + keyExtra : R;
    const [x0, y0] = p(r, a0), [x1, y1] = p(Ro, a0), [x2, y2] = p(Ro, a1), [x3, y3] = p(r, a1);
    const outer = key ? `L${f(x2)} ${f(y2)}` : `A${Ro} ${Ro} 0 0 1 ${f(x2)} ${f(y2)}`;
    parts.push(`M${f(x0)} ${f(y0)}L${f(x1)} ${f(y1)}${outer}L${f(x3)} ${f(y3)}A${r} ${r} 0 0 0 ${f(x0)} ${f(y0)}Z`);
  }
  const bottom = sill ? jambBottom - 3.2 : jambBottom;
  const top = spring + gap, h = (bottom - top - gap * courses) / courses;
  for (let k = 0; k < courses; k++) {
    const y = top + k * (h + gap), ext = k % 2 === 1 ? quoin : 0;
    parts.push(`M${f(cx - R - ext)} ${f(y)}H${f(cx - r)}V${f(y + h)}H${f(cx - R - ext)}Z`);
    parts.push(`M${f(cx + r)} ${f(y)}H${f(cx + R + ext)}V${f(y + h)}H${f(cx + r)}Z`);
  }
  if (sill) parts.push(`M${f(cx - R - 2.4)} ${f(jambBottom - 1.9)}H${f(cx + R + 2.4)}V${f(jambBottom)}H${f(cx - R - 2.4)}Z`);
  return parts.join("");
}
// Simplified for 16-32px: fewer, chunkier stones.
export const smallMarkPath = () => markPath({ n: 5, R: 21, r: 13, gapDeg: 4.5, keyExtra: 2.5, courses: 2, gap: 2.4, quoin: 2 });
// `node scripts/make-logo.mjs` rewrites src/components/logo-paths.ts and public/favicon.svg,
// then run `npm run icons` to rebuild the PNG/ICO favicons.
import { writeFileSync } from "node:fs";
writeFileSync(
  "src/components/logo-paths.ts",
  `// Brand mark: an arched Jerusalem-stone doorway ("in-door"). Nine voussoirs with a raised keystone,
// quoined jambs and a sill. Generated by scripts/make-logo.mjs; edit that script, not these strings.
export const MARK_VIEWBOX = "-3 -1 54 62";
/** Full detail, for 32px and up. */
export const MARK_PATH = "${markPath()}";
/** Five chunkier stones, for favicons and anything under 32px. */
export const MARK_PATH_SMALL = "${smallMarkPath()}";
`,
);
writeFileSync(
  "public/favicon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#1c1713"/><svg x="13" y="9" width="38" height="44" viewBox="-3 -1 54 62"><path fill="#b6894f" d="${smallMarkPath()}"/></svg></svg>\n`,
);
console.log("logo written");
